/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  github?: string;
  linkedin?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Body = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | {
      language?:
        | "typescript"
        | "javascript"
        | "csharp"
        | "c"
        | "cpp"
        | "rust"
        | "python"
        | "bash"
        | "json"
        | "html"
        | "css"
        | "text";
      filename?: string;
      code?: string;
      _type: "code";
      _key: string;
    }
>;

export type ContactLink = {
  _type: "contactLink";
  label?: string;
  url?: string;
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type ProfileReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "profile";
};

export type PostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "post";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: ProfileReference | PostReference | ProjectReference;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "tr";
  needsReview?: boolean;
  sourceId?: string;
  title?: string;
  description?: string;
  period?: string;
  technologies?: Array<string>;
  order?: number;
  links?: Array<
    {
      _key: string;
    } & ContactLink
  >;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "tr";
  needsReview?: boolean;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  publishedAt?: string;
  tags?: Array<string>;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Body;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Profile = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "tr";
  needsReview?: boolean;
  name?: string;
  role?: string;
  bio?: Body;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  cv?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  contacts?: Array<
    {
      _key: string;
    } & ContactLink
  >;
  reviewNote?: string;
  experience?: Array<{
    organization?: string;
    role?: string;
    period?: string;
    details?: Array<string>;
    _key: string;
  }>;
  education?: Array<{
    organization?: string;
    qualification?: string;
    period?: string;
    _key: string;
  }>;
  skills?: Array<{
    label?: string;
    items?: Array<string>;
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SiteSettings
  | SanityImageAssetReference
  | Body
  | ContactLink
  | TranslationMetadata
  | InternationalizedArrayReference
  | ProfileReference
  | PostReference
  | ProjectReference
  | InternationalizedArrayReferenceValue
  | Project
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityFileAssetReference
  | Profile
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: lib/content.ts
// Variable: PROFILE
// Query: *[_type=="profile" && language==$locale][0]{..., "cvUrl": cv.asset->url}
export type PROFILE_RESULT = {
  _id: string;
  _type: "profile";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "tr";
  needsReview?: boolean;
  name?: string;
  role?: string;
  bio?: Body;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  cv?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  contacts?: Array<
    {
      _key: string;
    } & ContactLink
  >;
  reviewNote?: string;
  experience?: Array<{
    organization?: string;
    role?: string;
    period?: string;
    details?: Array<string>;
    _key: string;
  }>;
  education?: Array<{
    organization?: string;
    qualification?: string;
    period?: string;
    _key: string;
  }>;
  skills?: Array<{
    label?: string;
    items?: Array<string>;
    _key: string;
  }>;
  cvUrl: string | null;
} | null;

// Source: lib/content.ts
// Variable: PROJECTS
// Query: *[_type=="project" && language==$locale] | order(order asc, title asc)
export type PROJECTS_RESULT = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "tr";
  needsReview?: boolean;
  sourceId?: string;
  title?: string;
  description?: string;
  period?: string;
  technologies?: Array<string>;
  order?: number;
  links?: Array<
    {
      _key: string;
    } & ContactLink
  >;
}>;

// Source: lib/content.ts
// Variable: POSTS
// Query: *[_type=="post" && language==$locale && defined(slug.current) && defined(publishedAt)] | order(publishedAt desc){..., "slug":slug.current}
export type POSTS_RESULT = Array<{
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "tr";
  needsReview?: boolean;
  title?: string;
  slug: string | null;
  excerpt?: string;
  publishedAt?: string;
  tags?: Array<string>;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Body;
}>;

// Source: lib/content.ts
// Variable: POST
// Query: *[_type=="post" && language==$locale && slug.current==$slug][0]{..., "slug":slug.current}
export type POST_RESULT = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: "en" | "tr";
  needsReview?: boolean;
  title?: string;
  slug: string | null;
  excerpt?: string;
  publishedAt?: string;
  tags?: Array<string>;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Body;
} | null;

// Source: lib/content.ts
// Variable: TRANSLATIONS
// Query: *[_type=="translation.metadata" && references($id)][0].translations[].value->{language,"slug":slug.current}
export type TRANSLATIONS_RESULT = Array<
  | {
      language: "en" | "tr" | null;
      slug: null;
    }
  | {
      language: "en" | "tr" | null;
      slug: string | null;
    }
  | null
> | null;

// Source: sanity/public.ts
// Variable: PUBLIC_QUERY
// Query: { "settings":*[_type=="siteSettings" && _id=="siteSettings"][0]{name}, "profile":*[_type=="profile" && language==$locale][0]{...,"cvUrl":cv.asset->url}, "projects":*[_type=="project" && language==$locale] | order(order asc,title asc), "posts":*[_type=="post" && language==$locale && defined(slug.current) && defined(publishedAt)] | order(publishedAt desc){...,"slug":slug.current}, "translations":*[_type=="translation.metadata"]{"members":translations[].value->{_id,language,"slug":slug.current}}}
export type PUBLIC_QUERY_RESULT = {
  settings: {
    name: string | null;
  } | null;
  profile: {
    _id: string;
    _type: "profile";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    language?: "en" | "tr";
    needsReview?: boolean;
    name?: string;
    role?: string;
    bio?: Body;
    portrait?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    cv?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    contacts?: Array<
      {
        _key: string;
      } & ContactLink
    >;
    reviewNote?: string;
    experience?: Array<{
      organization?: string;
      role?: string;
      period?: string;
      details?: Array<string>;
      _key: string;
    }>;
    education?: Array<{
      organization?: string;
      qualification?: string;
      period?: string;
      _key: string;
    }>;
    skills?: Array<{
      label?: string;
      items?: Array<string>;
      _key: string;
    }>;
    cvUrl: string | null;
  } | null;
  projects: Array<{
    _id: string;
    _type: "project";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    language?: "en" | "tr";
    needsReview?: boolean;
    sourceId?: string;
    title?: string;
    description?: string;
    period?: string;
    technologies?: Array<string>;
    order?: number;
    links?: Array<
      {
        _key: string;
      } & ContactLink
    >;
  }>;
  posts: Array<{
    _id: string;
    _type: "post";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    language?: "en" | "tr";
    needsReview?: boolean;
    title?: string;
    slug: string | null;
    excerpt?: string;
    publishedAt?: string;
    tags?: Array<string>;
    cover?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    body?: Body;
  }>;
  translations: Array<{
    members: Array<
      | {
          _id: string;
          language: "en" | "tr" | null;
          slug: null;
        }
      | {
          _id: string;
          language: "en" | "tr" | null;
          slug: string | null;
        }
      | null
    > | null;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type=="profile" && language==$locale][0]{..., "cvUrl": cv.asset->url}': PROFILE_RESULT;
    '*[_type=="project" && language==$locale] | order(order asc, title asc)': PROJECTS_RESULT;
    '*[_type=="post" && language==$locale && defined(slug.current) && defined(publishedAt)] | order(publishedAt desc){..., "slug":slug.current}': POSTS_RESULT;
    '*[_type=="post" && language==$locale && slug.current==$slug][0]{..., "slug":slug.current}': POST_RESULT;
    '*[_type=="translation.metadata" && references($id)][0].translations[].value->{language,"slug":slug.current}': TRANSLATIONS_RESULT;
    '{\n "settings":*[_type=="siteSettings" && _id=="siteSettings"][0]{name},\n "profile":*[_type=="profile" && language==$locale][0]{...,"cvUrl":cv.asset->url},\n "projects":*[_type=="project" && language==$locale] | order(order asc,title asc),\n "posts":*[_type=="post" && language==$locale && defined(slug.current) && defined(publishedAt)] | order(publishedAt desc){...,"slug":slug.current},\n "translations":*[_type=="translation.metadata"]{"members":translations[].value->{_id,language,"slug":slug.current}}\n}': PUBLIC_QUERY_RESULT;
  }
}
