import {defineType,defineField,defineArrayMember} from 'sanity';
const language=defineField({name:'language',title:'Language',type:'string',readOnly:true,options:{list:[{title:'English',value:'en'},{title:'Türkçe',value:'tr'}]},validation:r=>r.required()});
const review=defineField({name:'needsReview',title:'Needs content / translation review',type:'boolean',initialValue:true});
const contact=defineType({name:'contactLink',type:'object',fields:[defineField({name:'label',type:'string',validation:r=>r.required()}),defineField({name:'url',type:'url',validation:r=>r.required().uri({scheme:['https','http','mailto']})})]});
const body=defineType({name:'body',type:'array',of:[defineArrayMember({type:'block',styles:[{title:'Normal',value:'normal'},{title:'Heading 2',value:'h2'},{title:'Heading 3',value:'h3'},{title:'Quote',value:'blockquote'}],marks:{decorators:[{title:'Strong',value:'strong'},{title:'Emphasis',value:'em'},{title:'Code',value:'code'}],annotations:[{name:'link',type:'object',fields:[{name:'href',type:'url',validation:r=>r.required().uri({allowRelative:true,scheme:['https','http','mailto']})}]}]}}),defineArrayMember({type:'image',options:{hotspot:true},fields:[defineField({name:'alt',title:'Alternative text',type:'string',validation:r=>r.required()}),defineField({name:'caption',type:'string'})]}),defineArrayMember({type:'object',name:'code',title:'Code block',fields:[defineField({name:'language',type:'string',initialValue:'typescript',options:{list:['typescript','javascript','csharp','c','cpp','rust','python','bash','json','html','css','text']}}),defineField({name:'filename',type:'string'}),defineField({name:'code',type:'text',rows:16,validation:r=>r.required()})]})]});
const siteSettings=defineType({name:'siteSettings',title:'Site settings',type:'document',fields:[defineField({name:'name',title:'Site name',type:'string',validation:r=>r.required()}),defineField({name:'email',type:'string',validation:r=>r.email()}),defineField({name:'github',type:'url'}),defineField({name:'linkedin',type:'url'})]});
const profile=defineType({name:'profile',title:'Profile / CV',type:'document',fields:[language,review,defineField({name:'name',type:'string',validation:r=>r.required()}),defineField({name:'role',type:'string',initialValue:'Software Engineer',validation:r=>r.required()}),defineField({name:'bio',type:'body',validation:r=>r.required()}),defineField({name:'portrait',type:'image',options:{hotspot:true},fields:[defineField({name:'alt',type:'string'})]}),defineField({name:'cv',title:'CV PDF',type:'file',options:{accept:'.pdf'}}),defineField({name:'contacts',type:'array',of:[{type:'contactLink'}]}),defineField({name:'reviewNote',title:'Public note about dated records',type:'text'}),defineField({name:'experience',type:'array',of:[defineArrayMember({type:'object',fields:[{name:'organization',type:'string'},{name:'role',type:'string'},{name:'period',type:'string'},{name:'details',type:'array',of:[{type:'string'}]}],preview:{select:{title:'organization',subtitle:'period'}}})]}),defineField({name:'education',type:'array',of:[defineArrayMember({type:'object',fields:[{name:'organization',type:'string'},{name:'qualification',type:'string'},{name:'period',type:'string'}],preview:{select:{title:'organization',subtitle:'qualification'}}})]}),defineField({name:'skills',type:'array',of:[defineArrayMember({type:'object',fields:[{name:'label',type:'string'},{name:'items',type:'array',of:[{type:'string'}]}],preview:{select:{title:'label'}}})]})],preview:{select:{title:'name',subtitle:'language',media:'portrait'}}});
const post=defineType({name:'post',title:'Blog post',type:'document',fields:[language,review,defineField({name:'title',type:'string',validation:r=>r.required()}),defineField({name:'slug',type:'slug',options:{source:'title',maxLength:96,isUnique:async(slug,context)=>{
 const {document,getClient}=context;const id=document?._id.replace(/^drafts\./,'');
 return !(await getClient({apiVersion:'2026-02-01'}).fetch(`count(*[_type=="post" && language==$language && slug.current==$slug && !(_id in [$id,$draft])])`,{language:document?.language,slug,id,draft:`drafts.${id}`}));
 }},validation:r=>r.required()}),defineField({name:'excerpt',type:'text',rows:3,validation:r=>r.required().max(350)}),defineField({name:'publishedAt',title:'Publication date',description:'Publish immediately; this date orders articles and is not a scheduling control.',type:'datetime',validation:r=>r.required()}),defineField({name:'tags',type:'array',of:[{type:'string'}],options:{layout:'tags'}}),defineField({name:'cover',title:'Cover image (optional)',type:'image',options:{hotspot:true},fields:[defineField({name:'alt',type:'string',validation:r=>r.required()})]}),defineField({name:'body',type:'body',validation:r=>r.required().min(1)})],preview:{select:{title:'title',subtitle:'language',media:'cover'}}});
const project=defineType({name:'project',title:'Project',type:'document',fields:[language,review,defineField({name:'sourceId',title:'Import source identifier',type:'string',hidden:true,readOnly:true}),defineField({name:'title',type:'string',validation:r=>r.required()}),defineField({name:'description',type:'text',validation:r=>r.required()}),defineField({name:'period',title:'Date / period (if known)',type:'string'}),defineField({name:'technologies',type:'array',of:[{type:'string'}]}),defineField({name:'order',title:'Display order',type:'number',initialValue:0}),defineField({name:'links',title:'Real project links only',type:'array',of:[{type:'contactLink'}]})],preview:{select:{title:'title',subtitle:'language'}}});
export const schemaTypes=[contact,body,siteSettings,profile,post,project];
