'use client';
import {copy} from '@/lib/i18n';
import {readingTime,safeUrl} from '@/lib/content-policy';
import {articlePath,publishedArticleLinks} from '@/lib/seo';
import type {Locale,Post,Profile,Project,Translation} from '@/lib/types';
import {Contacts} from '@/components/contacts';
import {RichText,imageUrl} from './rich-text';
export function AboutView({locale,profile}:{locale:Locale;profile:Profile|null}){
 const t=copy[locale];if(!profile)return <main id="main"><h1>{t.about}</h1><p className="page-intro">{t.missingProfile}</p></main>;
 const portrait=imageUrl(profile.portrait,1100)||safeUrl(profile.portraitUrl),cv=safeUrl(profile.cvUrl);
 return <main id="main" className="about-page"><section className="about-intro"><div className="biography"><h1>{t.about}</h1><p className="role">{profile.name} · {profile.role}</p><RichText body={profile.bio}/><Contacts contacts={profile.contacts}/>{cv&&<><a className="cv-link" href={cv} download="CagatayDuruCV.pdf">{t.cv}</a>{cv==='/CagatayDuruCV.pdf'&&<span className="cv-source">{t.sourceCV}</span>}</>}</div>{portrait&&<img className="portrait" src={portrait} alt={profile.name} width={534} height={668} fetchPriority="high"/>}</section>
 {profile.reviewNote&&<aside className="review-note"><strong>{t.record}</strong>{profile.reviewNote}</aside>}
 <section className="cv-section"><h2>{t.experience}</h2><div>{(profile.experience||[]).map(e=><div className="experience-item" key={e._key}><h3>{e.organization}</h3><p className="position">{e.role}</p><p className="meta">{e.period}</p><ul>{e.details?.map(d=><li key={d}>{d}</li>)}</ul></div>)}</div></section>
 <section className="cv-section"><h2>{t.education}</h2><div>{(profile.education||[]).map(e=><div className="experience-item" key={e._key}><h3>{e.organization}</h3><p className="position">{e.qualification}</p><p className="meta">{e.period}</p></div>)}</div></section>
 <section className="cv-section"><h2>{t.skills}</h2><div>{(profile.skills||[]).map(s=><div className="skill-group" key={s._key}><h3>{s.label}</h3><p>{s.items?.join(' · ')}</p></div>)}</div></section>
 <section className="cv-section"><h2>{t.contact}</h2><div><p>{t.contactIntro}</p><Contacts contacts={profile.contacts}/></div></section></main>;
}
export function PortfolioView({locale,projects,fixture}:{locale:Locale;projects:Project[];fixture:boolean}){const t=copy[locale];return <main id="main" className="portfolio-page"><h1>{t.portfolio}</h1><p className="page-intro">{t.projectsIntro}</p>{locale==='tr'&&fixture&&<p className="meta" style={{marginBottom:24}}>{t.translationReview}</p>}{projects.length?projects.map((p,i)=><article className="project-row" key={p._id}><span className="project-number">{String(i+1).padStart(2,'0')}</span><div><div className="project-heading"><h2>{p.title}</h2>{p.period&&<span className="meta">{p.period}</span>}</div><p>{p.description}</p><p className="technologies">{p.technologies?.join(' · ')}</p>{!!p.links?.length&&<Contacts contacts={p.links}/>}</div></article>):<p>{t.missingProjects}</p>}</main>;}
export function BlogView({locale,posts}:{locale:Locale;posts:Post[]}){const t=copy[locale];return <main id="main" className="index-page"><h1>{t.blog}</h1>{posts.length?<div className="post-list">{posts.map(p=><article key={p._id}><div className="meta"><time dateTime={p.publishedAt}>{new Intl.DateTimeFormat(locale,{dateStyle:'long'}).format(new Date(p.publishedAt))}</time><span>{readingTime(p.body)} {t.reading}</span></div><h2><a href={articlePath(locale,p.slug)}>{p.title}</a></h2><p>{p.excerpt}</p></article>)}</div>:<div className="empty-blog"><h2>{t.emptyTitle}</h2><p>{t.empty}</p><div className="empty-links"><a href={`/${locale}/about/`}>{t.aboutLink}</a><a href={`/${locale}/portfolio/`}>{t.projectsLink}</a></div></div>}</main>;}
export function ArticleView({locale,post,profile,translations}:{locale:Locale;post:Post;profile:Profile|null;translations:Translation[]}){const t=copy[locale],paths=publishedArticleLinks(translations),cover=imageUrl(post.cover),portrait=profile&&(imageUrl(profile.portrait,220)||safeUrl(profile.portraitUrl));return <main id="main" className="article-layout"><aside className="author-sidebar">{portrait&&<img src={portrait} alt={profile?.name||'Çağatay Duru'} width={100} height={100}/>}<div><h2>{profile?.name||'Çağatay Duru'}</h2><p>{profile?.role||'Software Engineer'}</p><a href={`/${locale}/about/`}>{t.aboutLink}</a><Contacts contacts={profile?.contacts}/></div></aside><article className="article"><h1>{post.title}</h1><div className="meta"><time dateTime={post.publishedAt}>{new Intl.DateTimeFormat(locale,{dateStyle:'long'}).format(new Date(post.publishedAt))}</time><span>{readingTime(post.body)} {t.reading}</span></div>{Object.entries(paths).filter(([l])=>l!==locale).map(([l,href])=><nav className="article-translations" key={l}><a href={href} hrefLang={l}>{l==='tr'?'Türkçe oku':'Read in English'}</a></nav>)}<p className="excerpt">{post.excerpt}</p>{cover&&<img className="article-cover" src={cover} alt={post.cover?.alt||''}/>}<RichText body={post.body}/>{!!post.tags?.length&&<p className="tags">{post.tags.join(' · ')}</p>}<p style={{marginTop:40}}><a href={`/${locale}/`}>{t.back}</a></p></article></main>;}
